// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD55rH-lMMkFMfL1J8pPVQwmW_yk314a64',
    appId: '1:724389457144:web:8ef138ee78dbc4fe351f0d',
    messagingSenderId: '724389457144',
    projectId: 'fir-auth-module-16314',
    authDomain: 'fir-auth-module-16314.firebaseapp.com',
    storageBucket: 'fir-auth-module-16314.firebasestorage.app',
    measurementId: 'G-VHD7DRELM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6sSMDRL1D5j4bVjjLShEZ93nLNxFyM38',
    appId: '1:724389457144:android:61d894146bd3524d351f0d',
    messagingSenderId: '724389457144',
    projectId: 'fir-auth-module-16314',
    storageBucket: 'fir-auth-module-16314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKO1D6D5JEIuPSEReUN6CFs7I0NyN4pnM',
    appId: '1:724389457144:ios:f4b827008de14dab351f0d',
    messagingSenderId: '724389457144',
    projectId: 'fir-auth-module-16314',
    storageBucket: 'fir-auth-module-16314.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKO1D6D5JEIuPSEReUN6CFs7I0NyN4pnM',
    appId: '1:724389457144:ios:f4b827008de14dab351f0d',
    messagingSenderId: '724389457144',
    projectId: 'fir-auth-module-16314',
    storageBucket: 'fir-auth-module-16314.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD55rH-lMMkFMfL1J8pPVQwmW_yk314a64',
    appId: '1:724389457144:web:494a4652c6cdbe75351f0d',
    messagingSenderId: '724389457144',
    projectId: 'fir-auth-module-16314',
    authDomain: 'fir-auth-module-16314.firebaseapp.com',
    storageBucket: 'fir-auth-module-16314.firebasestorage.app',
    measurementId: 'G-G1NB74SPEL',
  );
}
